# Generated by Django 2.1.5 on 2019-03-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190226_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['user', '-post_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['blog', 'date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Blogger', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Blog', verbose_name='Comment made on post titled'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Comment date'),
        ),
    ]
