# Generated by Django 2.1.5 on 2019-03-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190303_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='biography',
            field=models.TextField(blank=True, default='', help_text='Biography for blogger info', max_length=1000),
        ),
    ]
